# .streamlit/config.toml

[theme]
primaryColor = "#FF69B4"             # Hot Pink
backgroundColor = "#FFFFFF"          # White
secondaryBackgroundColor = "#FFB6C1" # Light Pink
textColor = "#4B0082"                # Indigo
font = "monospace"
fontSize = 16
